export default [
	{
		login: 'arifpro',
		id: 45432079,
		node_id: 'MDQ6VXNlcjQ1NDMyMDc5',
		avatar_url: 'https://avatars.githubusercontent.com/u/45432079?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/arifpro',
		html_url: 'https://github.com/arifpro',
		followers_url: 'https://api.github.com/users/arifpro/followers',
		following_url: 'https://api.github.com/users/arifpro/following{/other_user}',
		gists_url: 'https://api.github.com/users/arifpro/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/arifpro/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/arifpro/subscriptions',
		organizations_url: 'https://api.github.com/users/arifpro/orgs',
		repos_url: 'https://api.github.com/users/arifpro/repos',
		events_url: 'https://api.github.com/users/arifpro/events{/privacy}',
		received_events_url: 'https://api.github.com/users/arifpro/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'tarikulIslamNahid',
		id: 55321283,
		node_id: 'MDQ6VXNlcjU1MzIxMjgz',
		avatar_url: 'https://avatars.githubusercontent.com/u/55321283?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/tarikulIslamNahid',
		html_url: 'https://github.com/tarikulIslamNahid',
		followers_url: 'https://api.github.com/users/tarikulIslamNahid/followers',
		following_url: 'https://api.github.com/users/tarikulIslamNahid/following{/other_user}',
		gists_url: 'https://api.github.com/users/tarikulIslamNahid/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/tarikulIslamNahid/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/tarikulIslamNahid/subscriptions',
		organizations_url: 'https://api.github.com/users/tarikulIslamNahid/orgs',
		repos_url: 'https://api.github.com/users/tarikulIslamNahid/repos',
		events_url: 'https://api.github.com/users/tarikulIslamNahid/events{/privacy}',
		received_events_url: 'https://api.github.com/users/tarikulIslamNahid/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'ebrahimrizve',
		id: 56842129,
		node_id: 'MDQ6VXNlcjU2ODQyMTI5',
		avatar_url: 'https://avatars.githubusercontent.com/u/56842129?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/ebrahimrizve',
		html_url: 'https://github.com/ebrahimrizve',
		followers_url: 'https://api.github.com/users/ebrahimrizve/followers',
		following_url: 'https://api.github.com/users/ebrahimrizve/following{/other_user}',
		gists_url: 'https://api.github.com/users/ebrahimrizve/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/ebrahimrizve/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/ebrahimrizve/subscriptions',
		organizations_url: 'https://api.github.com/users/ebrahimrizve/orgs',
		repos_url: 'https://api.github.com/users/ebrahimrizve/repos',
		events_url: 'https://api.github.com/users/ebrahimrizve/events{/privacy}',
		received_events_url: 'https://api.github.com/users/ebrahimrizve/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'iamsaif6',
		id: 57500210,
		node_id: 'MDQ6VXNlcjU3NTAwMjEw',
		avatar_url: 'https://avatars.githubusercontent.com/u/57500210?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/iamsaif6',
		html_url: 'https://github.com/iamsaif6',
		followers_url: 'https://api.github.com/users/iamsaif6/followers',
		following_url: 'https://api.github.com/users/iamsaif6/following{/other_user}',
		gists_url: 'https://api.github.com/users/iamsaif6/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/iamsaif6/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/iamsaif6/subscriptions',
		organizations_url: 'https://api.github.com/users/iamsaif6/orgs',
		repos_url: 'https://api.github.com/users/iamsaif6/repos',
		events_url: 'https://api.github.com/users/iamsaif6/events{/privacy}',
		received_events_url: 'https://api.github.com/users/iamsaif6/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Yeasiin',
		id: 62445940,
		node_id: 'MDQ6VXNlcjYyNDQ1OTQw',
		avatar_url: 'https://avatars.githubusercontent.com/u/62445940?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Yeasiin',
		html_url: 'https://github.com/Yeasiin',
		followers_url: 'https://api.github.com/users/Yeasiin/followers',
		following_url: 'https://api.github.com/users/Yeasiin/following{/other_user}',
		gists_url: 'https://api.github.com/users/Yeasiin/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Yeasiin/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Yeasiin/subscriptions',
		organizations_url: 'https://api.github.com/users/Yeasiin/orgs',
		repos_url: 'https://api.github.com/users/Yeasiin/repos',
		events_url: 'https://api.github.com/users/Yeasiin/events{/privacy}',
		received_events_url: 'https://api.github.com/users/Yeasiin/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'khalidbinahsan',
		id: 62564641,
		node_id: 'MDQ6VXNlcjYyNTY0NjQx',
		avatar_url: 'https://avatars.githubusercontent.com/u/62564641?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/khalidbinahsan',
		html_url: 'https://github.com/khalidbinahsan',
		followers_url: 'https://api.github.com/users/khalidbinahsan/followers',
		following_url: 'https://api.github.com/users/khalidbinahsan/following{/other_user}',
		gists_url: 'https://api.github.com/users/khalidbinahsan/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/khalidbinahsan/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/khalidbinahsan/subscriptions',
		organizations_url: 'https://api.github.com/users/khalidbinahsan/orgs',
		repos_url: 'https://api.github.com/users/khalidbinahsan/repos',
		events_url: 'https://api.github.com/users/khalidbinahsan/events{/privacy}',
		received_events_url: 'https://api.github.com/users/khalidbinahsan/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'sayedrazo',
		id: 63364395,
		node_id: 'MDQ6VXNlcjYzMzY0Mzk1',
		avatar_url: 'https://avatars.githubusercontent.com/u/63364395?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/sayedrazo',
		html_url: 'https://github.com/sayedrazo',
		followers_url: 'https://api.github.com/users/sayedrazo/followers',
		following_url: 'https://api.github.com/users/sayedrazo/following{/other_user}',
		gists_url: 'https://api.github.com/users/sayedrazo/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/sayedrazo/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/sayedrazo/subscriptions',
		organizations_url: 'https://api.github.com/users/sayedrazo/orgs',
		repos_url: 'https://api.github.com/users/sayedrazo/repos',
		events_url: 'https://api.github.com/users/sayedrazo/events{/privacy}',
		received_events_url: 'https://api.github.com/users/sayedrazo/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'HassShishir',
		id: 69468876,
		node_id: 'MDQ6VXNlcjY5NDY4ODc2',
		avatar_url: 'https://avatars.githubusercontent.com/u/69468876?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/HassShishir',
		html_url: 'https://github.com/HassShishir',
		followers_url: 'https://api.github.com/users/HassShishir/followers',
		following_url: 'https://api.github.com/users/HassShishir/following{/other_user}',
		gists_url: 'https://api.github.com/users/HassShishir/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/HassShishir/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/HassShishir/subscriptions',
		organizations_url: 'https://api.github.com/users/HassShishir/orgs',
		repos_url: 'https://api.github.com/users/HassShishir/repos',
		events_url: 'https://api.github.com/users/HassShishir/events{/privacy}',
		received_events_url: 'https://api.github.com/users/HassShishir/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'RiyadMahmud2021',
		id: 79051584,
		node_id: 'MDQ6VXNlcjc5MDUxNTg0',
		avatar_url: 'https://avatars.githubusercontent.com/u/79051584?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/RiyadMahmud2021',
		html_url: 'https://github.com/RiyadMahmud2021',
		followers_url: 'https://api.github.com/users/RiyadMahmud2021/followers',
		following_url: 'https://api.github.com/users/RiyadMahmud2021/following{/other_user}',
		gists_url: 'https://api.github.com/users/RiyadMahmud2021/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/RiyadMahmud2021/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/RiyadMahmud2021/subscriptions',
		organizations_url: 'https://api.github.com/users/RiyadMahmud2021/orgs',
		repos_url: 'https://api.github.com/users/RiyadMahmud2021/repos',
		events_url: 'https://api.github.com/users/RiyadMahmud2021/events{/privacy}',
		received_events_url: 'https://api.github.com/users/RiyadMahmud2021/received_events',
		type: 'User',
		site_admin: false,
	},
];
