export default {
	login: 'main1479',
	id: 57148171,
	node_id: 'MDQ6VXNlcjU3MTQ4MTcx',
	avatar_url: 'https://avatars.githubusercontent.com/u/57148171?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/main1479',
	html_url: 'https://github.com/main1479',
	followers_url: 'https://api.github.com/users/main1479/followers',
	following_url: 'https://api.github.com/users/main1479/following{/other_user}',
	gists_url: 'https://api.github.com/users/main1479/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/main1479/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/main1479/subscriptions',
	organizations_url: 'https://api.github.com/users/main1479/orgs',
	repos_url: 'https://api.github.com/users/main1479/repos',
	events_url: 'https://api.github.com/users/main1479/events{/privacy}',
	received_events_url: 'https://api.github.com/users/main1479/received_events',
	type: 'User',
	site_admin: false,
	name: 'Mainul Islam',
	company: null,
	blog: '',
	location: 'Bangladesh',
	email: null,
	hireable: true,
	bio: " ❤Always love to learn something new ❤ I love to do web design and development and I'm very passionate about it.",
	twitter_username: 'main1479',
	public_repos: 66,
	public_gists: 1,
	followers: 9,
	following: 26,
	created_at: '2019-10-29T16:28:00Z',
	updated_at: '2021-06-25T09:29:21Z',
};